//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultant_Project
    {
        public int Id { get; set; }
        public System.DateTime ProjStartDate { get; set; }
        public System.DateTime ProjEndDate { get; set; }
        public bool BillableStatus { get; set; }
        public Nullable<int> BillableDaysMonth { get; set; }
        public Nullable<int> BillableDaysYTD { get; set; }
        public int ProjectId { get; set; }
        public int ConsultantId { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Consultant Consultant { get; set; }
    }
}
