//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DashboardModelContainer : DbContext
    {
        public DashboardModelContainer()
            : base("name=PlacementDashboardEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Consultant_Project> Consultant_Project { get; set; }
        public virtual DbSet<Consultant> Consultants { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
    }
}
