//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Consultant_Projects = new HashSet<Consultant_Project>();
        }
    
        public int Id { get; set; }
        public string ProjectName { get; set; }
    
        public virtual ICollection<Consultant_Project> Consultant_Projects { get; set; }
    }
}
